channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*
  - numpy=2.2.*
  - scipy=1.15.*
  - pandas=2.2.*
  - matplotlib=3.10.*
  - cvxpy=1.5.*
  - scikit-learn=1.6.*
  - tqdm=4.67.*
  - pip
  - pip:
    - .[dev,jupyter,jax]
    